#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Dummy variables to be able to use the configuration panel
ynh_app_setting_set --key=join --value=""
ynh_app_setting_set --key=leave --value=""

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration file..."

mkdir -p "$data_dir"
ynh_config_add --template="local.conf" --destination="$data_dir/local.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Enable a systemd service
ynh_systemctl --service="$service" --action="enable"
# Start a systemd service
ynh_systemctl --service="$service" --action="restart"

yunohost service add "$service" --description "ZeroTier"

#=================================================
# GENERATING IDENTITY
#=================================================
ynh_script_progression "Waiting for identity generation..."

wait_seconds=30
until [ -f "$data_dir/identity.public" ]; do
    sleep 1
    if [ "$((wait_seconds--))" -eq 0 ]; then
        ynh_print_warn "Identity generation timed out."
        break
    fi
done

if [ -f "$data_dir/identity.public" ]; then
    address=$(echo "$(zerotier-cli info)" | cut -d " " -f 3)
    ynh_app_setting_set --key="address" --value="$address"
else
    ynh_app_setting_set --key="address" --value="unknown"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
