#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

service="zerotier-one"
ynh_app_setting_set --app="$app" --key=service --value=$service

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration file..." --weight=2

ynh_add_config --template="local.conf" --destination="$install_dir/local.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=2

# Enable a systemd service
ynh_systemd_action --service_name="$service" --action="enable"
# Start a systemd service
ynh_systemd_action --service_name="$service" --action="restart"

yunohost service add "$service" --description "ZeroTier"

#=================================================
# GENERATING IDENTITY
#=================================================
ynh_script_progression --message="Waiting for identity generation..." --weight=2

wait_seconds=30
until [ -f "$install_dir/identity.public" ]; do
    sleep 1
    if [ "$((wait_seconds--))" -eq 0 ]; then
        ynh_print_warn --message="Identity generation timed out."
    fi
done

if [ -f "$install_dir/identity.public" ]; then
    address=$(cut -d : -f 1 "$install_dir/identity.public")
    ynh_app_setting_set --app="$app" --key="address" --value="$address"
else
    ynh_app_setting_set --app="$app" --key="address" --value="unknown"
fi


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
