#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$service" >/dev/null; then
    ynh_script_progression "Removing $app service..."
    yunohost service remove "$service"
fi

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
