#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Dummy variables to be able to use the configuration panel
if [ -z "${join:-}" ]; then
     ynh_app_setting_set --key=join --value=""
fi
if [ -z "${leave:-}" ]; then
     ynh_app_setting_set --key=leave --value=""
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Enable a systemd service
ynh_systemctl --service="$service" --action="enable"
# Start a systemd service
ynh_systemctl --service="$service" --action="restart"

yunohost service add "$service" --description "ZeroTier"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [[ -z "${address:-}" ]] || [[ "$address" == "unknown" ]]; then

    wait_seconds=30
    until [ -f "$install_dir/identity.public" ]; do
        sleep 1
        if [ "$((wait_seconds--))" -eq 0 ]; then
            ynh_print_warn "Identity generation timed out."
            break
        fi
    done

    if [ -f "$install_dir/identity.public" ]; then
        address=$(echo "$(zerotier-cli info)" | cut -d " " -f 3)
        ynh_app_setting_set --key="address" --value="$address"
    else
        ynh_print_warn "Identity file is missing. Please report to YunoHost Support if your ZeroTier instance does not work."
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
