#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$service --action="stop" --log_path="systemd" --line_match="Stopped ZeroTier One" --timeout=15

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

if [[ -z "${address:-}" ]] || [[ "$address" == "unknown" ]]; then
    if [ -f "$install_dir/identity.public" ]; then
        address=$(cut -d : -f 1 "$install_dir/identity.public")
        ynh_app_setting_set --app="$app" --key="address" --value="$address"
    else
        ynh_print_warn --message="Identity file is missing. Please report to YunoHost Support if your ZeroTier instance does not work."
    fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=2

# Enable a systemd service
ynh_systemd_action --service_name="$service" --action="enable"
# Start a systemd service
ynh_systemd_action --service_name="$service" --action="restart"

yunohost service add "$service" --description "ZeroTier"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
